name: Convert HTML to PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: html to pdf
      uses: fifsky/html-to-pdf-action@master
      with:
        htmlFile: ./src/index.html
        outputFile: ./docs/Polars_Cheat_Sheet_Ja.pdf
        pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./public/resume.pdf
        git commit -m 'Add generated PDF'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
